import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  UI_OVERRIDES_RELATIVE,
  combineInstanceOverrides,
  mergeInstanceOverrides,
  planInstancePersistence,
  renderUiOverridesModule,
  writeUiOverridesModule
} from "./ui-overrides.js";

const temporary: string[] = [];

afterEach(() => {
  for (const root of temporary.splice(0)) fs.rmSync(root, { recursive: true, force: true });
});

describe("instance overrides", () => {
  it("keeps a dragged kit label on its path and reverts a node with no path", () => {
    const planned = planInstancePersistence([
      {
        instancePath: "root/scripts/ui/UiStyle.lua|Label#2",
        applied: [] as string[],
        skipped: [
          { key: "left", reason: "kit_internal_geometry" },
          { key: "top", reason: "kit_internal_geometry" }
        ],
        revert: { left: null, top: null }
      },
      {
        applied: [] as string[],
        skipped: [{ key: "width", reason: "widget_not_found" }],
        revert: { width: 10 }
      }
    ], [
      { path: "root/scripts/ui/UiStyle.lua|Label#2", props: { left: 12, top: 40 } }
    ]);
    expect(planned.revertDetails).toHaveLength(1);
    expect(planned.revertDetails[0]?.revert).toEqual({ width: 10 });
    expect(planned.updates[0]).toMatchObject({
      path: "root/scripts/ui/UiStyle.lua|Label#2",
      props: { left: 12, top: 40 },
      removeKeys: []
    });
  });

  it("drops keys that were written into Lua so restart does not apply them twice", () => {
    const merged = mergeInstanceOverrides(
      [{ path: "root/a", props: { left: 1, text: "旧" } }],
      [{ path: "root/a", props: { left: 9, text: "新" }, removeKeys: ["text"] }]
    );
    expect(merged).toEqual([{ path: "root/a", props: { left: 9 } }]);
    const planned = planInstancePersistence([
      {
        instancePath: "root/a",
        applied: ["text", "left"],
        skipped: [],
        revert: { text: "旧" }
      }
    ], [
      { path: "root/a", props: { text: "新", left: 9 } }
    ]);
    expect(planned.revertDetails).toHaveLength(0);
    expect(planned.updates[0]?.removeKeys).toEqual(["left"]);
    const kept = mergeInstanceOverrides([], planned.updates);
    expect(kept).toEqual([{ path: "root/a", props: { text: "新" } }]);
  });

  it("renders a require-able lua module and lets the current file clear a stale path", () => {
    const text = renderUiOverridesModule([
      { path: "root/scripts/ui/UiStyle.lua|Label#1", props: { position: "absolute", left: 3, backgroundColor: [1, 2, 3, 255] } }
    ]);
    expect(text).toContain('["root/scripts/ui/UiStyle.lua|Label#1"]');
    expect(text).toContain('position = "absolute"');
    expect(text).toContain("left = 3");
    expect(text).toContain("{ 1, 2, 3, 255 }");
    expect(text.startsWith("-- Generated by TapMakerWork")).toBe(true);
    const combined = combineInstanceOverrides(
      [{ path: "root/a", props: { left: 1 } }, { path: "root/b", props: { top: 2 } }],
      [{ path: "root/b", props: { top: 9 } }],
      ["root/a"]
    );
    expect(combined).toEqual([{ path: "root/b", props: { top: 9 } }]);
  });

  it("writes the module once and skips a rewrite when the replay did not change", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "tapmaker-overrides-"));
    temporary.push(root);
    const instances = [{ path: "root/x", props: { top: 8 } }];
    writeUiOverridesModule(root, instances);
    const file = path.join(root, UI_OVERRIDES_RELATIVE);
    const first = fs.readFileSync(file, "utf8");
    const stamped = fs.statSync(file).mtimeMs;
    writeUiOverridesModule(root, instances);
    expect(fs.readFileSync(file, "utf8")).toBe(first);
    expect(fs.statSync(file).mtimeMs).toBe(stamped);
  });
});
